[package]
name = "minmax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
arrow = "47.0.0"
polars = { version = "0.33.2", features = ["moment"] }
statrs = "0.12"
